export const USER = 'USER'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const TOKEN = 'TOKEN'
export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED'
